### ISSUE TITLE
How to fix "ImportError: cannot import name 'dataclass'"?

### ISSUE THREAD

**Issue by htliu6** [MSNLAB/SmartEye#1]
Excuse me, I encountered following issues when setting up edge node. Have you ever notice this problem? Thanks!
```
$ python3 edge_main.py -f ~/cutout1.mp4 -i 50
Traceback (most recent call last):
  File "edge_main.py", line 14, in <module>
    from local.decision_engine import DecisionEngine
  File "/home/htliu/SmartEye/local/decision_engine.py", line 4, in <module>
    from model_manager.model_cache import get_fastest_model, get_most_precise_model
  File "/home/htliu/SmartEye/model_manager/model_cache.py", line 3, in <module>
    import torch
  File "/home/htliu/.local/lib/python3.6/site-packages/torch/__init__.py", line 627, in <module>
    import torch.utils.data
  File "/home/htliu/.local/lib/python3.6/site-packages/torch/utils/data/__init__.py", line 6, in <module>
    from .dataloader import DataLoader, _DatasetKind, get_worker_info
  File "/home/htliu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 21, in <module>
    from . import _utils
  File "/home/htliu/.local/lib/python3.6/site-packages/torch/utils/data/_utils/__init__.py", line 45, in <module>
    from . import worker, signal_handling, pin_memory, collate, fetch
  File "/home/htliu/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 10, in <module>
    from dataclasses import dataclass
ImportError: cannot import name 'dataclass'
```

**Comment by ZhiyanWXZ** [comment]
I'm sorry that I have never met the issue you have encountered. From the error content, I think the pytorch version causes the problem. Have you correctly installed the pytorch package?

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Apr 26, 2022 02:51 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[MSNLAB/SmartEye] How to fix "ImportError: cannot import name 'dataclass'"? (Issue #1)

&nbsp;



 
Excuse me, I encountered following issues when setting up edge node. Have you ever notice this problem? Thanks!
 $ python3 edge_main.py -f ~/cutout1.mp4 -i 50 Traceback (most recent call last):   File "edge_main.py", line 14, in <module&gt;     from local.decision_engine import DecisionEngine   File "/home/htliu/SmartEye/local/decision_engine.py", line 4, in <module&gt;     from model_manager.model_cache import get_fastest_model, get_most_precise_model   File "/home/htliu/SmartEye/model_manager/model_cache.py", line 3, in <module&gt;     import torch   File "/home/htliu/.local/lib/python3.6/site-packages/torch/__init__.py", line 627, in <module&gt;     import torch.utils.data   File "/home/htliu/.local/lib/python3.6/site-packages/torch/utils/data/__init__.py", line 6, in <module&gt;     from .dataloader import DataLoader, _DatasetKind, get_worker_info   File "/home/htliu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 21, in <module&gt;     from . import _utils   File "/home/htliu/.local/lib/python3.6/site-packages/torch/utils/data/_utils/__init__.py", line 45, in <module&gt;     from . import worker, signal_handling, pin_memory, collate, fetch   File "/home/htliu/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 10, in <module&gt;     from dataclasses import dataclass ImportError: cannot import name 'dataclass'

**Comment by htliu6** [comment]
Thanks for your kindly reply! I install pytorch using the following command line
 `pip install torch==1.8.0+cpu torchvision==0.9.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html`
from [https://pytorch.org/get-started/previous-versions/#linux-and-windows-11](https://pytorch.org/get-started/previous-versions/#linux-and-windows-11), and everything gets OK when installation finished.

I wonder whether this matters if I have no GPU with my VM.

**Comment by ZhiyanWXZ** [comment]
Using GPU or no GPU is alright. Our framework support both.

--------------原始邮件--------------
发件人："htliu6 ***@***.***&gt;;
发送时间：2022年4月26日(星期二) 下午3:31
收件人："MSNLAB/SmartEye" ***@***.***&gt;;
抄送："王学智 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [MSNLAB/SmartEye] How to fix "ImportError: cannot import name 'dataclass'"? (Issue #1)
-----------------------------------

 

 
Thanks for your kindly reply! I install pytorch using the following command line
 pip install torch==1.8.0+cpu torchvision==0.9.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
 from https://pytorch.org/get-started/previous-versions/#linux-and-windows-11, and everything gets OK when installation finished.
 
I wonder whether this matters if I have no GPU with my VM.

**Comment by htliu6** [comment]
Thanks for your reply! BTW, I wonder which **version** of opencv-python you adopted when running this repo. Thanks!

**Comment by ZhiyanWXZ** [comment]
I used an arm achitecture computer, so the version is 3.2.0+dfsg-4build2 arm64.&nbsp; I do not know if this can help you.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "htliu6"; 
Date: 2022年4月27日(星期三) 下午4:57
To: "MSNLAB/SmartEye"; 
Cc: ***@***.***>; "Comment"; 
Subject: Re: [MSNLAB/SmartEye] How to fix &quot;ImportError: cannot import name 'dataclass'&quot;? (Issue #1)

&nbsp;


 
Thanks for your reply! BTW, I wonder which version of opencv-python you adopted when running this repo. Thanks!
