### ISSUE TITLE
nvalid load key, 'v'.

### ISSUE THREAD

**Issue by shichaoya** [MSNLAB/SmartEye#2]
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by shichaoya** [comment]
2023-05-05 09:07:48.184 | INFO     | __main__:<module>:52 - local models are loading...
Traceback (most recent call last):
  File "edge_main.py", line 53, in <module>
    edge_globals.loaded_model = load_models(edge_object_detection_model)
  File "/home/xia000/桌面/SmartEye/SmartEye-master/model_manager/model_cache.py", line 18, in load_models
    file_load = torch.load(weight_files_path)
  File "/home/xia000/anaconda3/envs/Pytorch2/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/xia000/anaconda3/envs/Pytorch2/lib/python3.6/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
